name: BlueMapAreaControl
version: '${project.version}'
main: com.technicjelle.bluemapareacontrol.BlueMapAreaControl
api-version: 1.13
depend:
  - BlueMap
authors:
  - TechnicJelle
description: '${project.description}'
website: '${project.url}'
